### ISSUE TITLE
Six shooter image disappears with zoom.

### ISSUE THREAD

**Issue by simplyrohan** [pygame-community/pyga.me#14]
Hello! I noticed that the Six Shooter image at the bottom of the page had disappeared. After some poking around, I discovered by setting my zoom level to 90% or below, the image appeared. 100% or above, it was as if it didn't exist. In case, you were wondering, I set my zoom level through the Cmnd/Ctrl and + keys. This issue is probably occurring because my monitor size is to small. The fix is probably to set the image's size with dynamic units (vw, vh).

**Comment by oddbookworm** [comment]
@simplyrohan can you also provide the OS, browser, and monitor size you saw this on?

**Comment by simplyrohan** [comment]
Of course,

OS: macOS Ventura
Browser: Chrome
Monitor Size: 2560 × 1600

Let me know if you need any more info!

**Comment by novialriptide** [comment]
This has been a thing for a while due to the website's development being rushed. Six Shooter will no longer have its own individual image and will probably be moved to the **Pygame Powered** section.

This will be taken care of during the Tailwind CSS rework.

**Comment by novialriptide** [comment]
Six Shooter has been removed, will return soon.
