### ISSUE TITLE
New sphinx theme for the pygame documentation

### ISSUE THREAD

**Issue by novialriptide** [pygame-community/pyga.me#2]
This is just ugly... We should have a button that takes you to the "Classic/Modern" documentation.

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/35881688/218564441-a672de52-5157-40d8-9df8-ce81fe9f41d4.png">

**Comment by itzpr3d4t0r** [comment]
I kinda like the readthedocs theme https://sphinx-themes.org/sample-sites/sphinx-rtd-theme/long-page/.

**Comment by novialriptide** [comment]
> I kinda like the readthedocs theme https://sphinx-themes.org/sample-sites/sphinx-rtd-theme/long-page/.
> Btw this is a link to the various themes: https://sphinx-themes.org/#themes.

I plan on making my own theme to keep the pygame docs unique somehow

**Comment by SSS-Says-Snek** [comment]
I personally like Furo a lot (shown in https://hisock.readthedocs.io). We can modify it to somehow incorporate some green into the theme though

**Comment by Notenlish** [comment]
This pr in pygame-ce does this but it doesn't change the docs theme, it modifies the existing one https://github.com/pygame-community/pygame-ce/pull/2122

**Comment by novialriptide** [comment]
Fixed: https://github.com/pygame-community/pygame-ce/pull/2122
